# Problem 1

In [5]:
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
x = np.random.randint(0, 10, size=(5,))
print(x)

# 3 - matris'in boyutunu öğrenin
print(x.shape)

# 4 - matris'i yeniden boyutlandırın
x = x.reshape((5, 1))
print(x)

# 5 - matris'in boyut sayısını öğrenin
print(x.ndim)


[8 0 5 7 9]
(5,)
[[8]
 [0]
 [5]
 [7]
 [9]]
2


# Problem 2

In [7]:
import numpy as np

# 1 - 0 ile 10 arasında bulunan tek sayılardan matris üretin
x = np.random.choice([1, 3, 5, 7, 9], size=(6,))
print(x)

# 2 - Oluşturduğunuz matrisi parçalayın
y, z = np.split(x, 2)
print(y)
print(z)

# 3 - Parçalanmış matrisleri birleştirin
a = np.concatenate((y, z))
print(a)




[1 9 9 9 9 7]
[1 9 9]
[9 9 7]
[1 9 9 9 9 7]


# Problem 3

In [9]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
sayilar = np.arange(5, 100, 2)
x = np.random.choice(sayilar, size=10)
print(x)

# 2 - matris'in özelliklerini inceleyin
print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)


[77 21  7  7 81 85 85 17  7 59]
(10,)
1
10
int64
