# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
arr = np.array([12, 4, 9, 1, 7])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın
sorted_arr = np.sort(arr)

print("Sıralı dizi:", sorted_arr)



Sıralı dizi: [ 1  4  7  9 12]


# Problem 2

In [1]:
import numpy as np

# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a1 = np.array([10, 15, 30, 45, 60])

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
a2 = np.arange(5, 16)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
a3 = np.arange(50, 101, 5)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
a4 = np.zeros(10)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
a5 = np.ones(10)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
a6 = np.linspace(0, 100, 5)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
a7 = np.random.randint(10, 31, 5)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
a8 = np.random.uniform(-1, 1, 10)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
a9 = np.random.randint(10, 51, (3, 5))

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir_toplam = np.sum(a9, axis=1)  # satır toplamları
sutun_toplam = np.sum(a9, axis=0)  # sütun toplamları

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
en_buyuk = np.max(a9)
en_kucuk = np.min(a9)
ortalama = np.mean(a9)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
en_buyuk_indeks = np.unravel_index(np.argmax(a9), a9.shape)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
a13 = np.arange(10, 21)
ilk_3 = a13[:3]

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
ters = a13[::-1]

# 15- Üretilen matrisin ilk satırını seçiniz.
ilk_satir = a9[0]

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
eleman_2_3 = a9[1, 2]

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
ilk_sutun = a9[:, 0]

# 18- Üretilen matrisin her bir elemanının karesini alınız.
karesi = np.square(a9)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
a19 = np.random.randint(-50, 51, (3, 5))
pozitif_ciftler = a19[(a19 > 0) & (a19 % 2 == 0)]

# Örnek çıktı kontrolü için birkaçını yazdırabiliriz:
print("19. Soru Matrisi:\n", a19)
print("Pozitif çift sayılar:", pozitif_ciftler)



19. Soru Matrisi:
 [[-31 -40  10  26 -15]
 [-46 -10   7 -33  29]
 [-23  29 -25  13 -40]]
Pozitif çift sayılar: [10 26]
